package: collaborate
version: '1.2.0'
author: Friends Of REDAXO
pjax: true
supportpage: https://github.com/FriendsOfREDAXO/collaborate

requires:
    php: '>=8.0'
    redaxo: ^5.12

console_commands:
    collaborate: rex_collaborate_console 

websocket-server-port: 6789
websocket-client-port: 443
websocket-path: 'wss'
